TalentosApp/TalentosApp.Web/Controllers/MuseFiltroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TalentosApp.Contractos.Servicios;
using TalentosApp.Enumeradores;
using TalentosApp.TransferenciaDatos.Entradas;

namespace TalentosApp.Web.Controllers
{
    public class MuseFiltroController : Controller
    {
        private readonly IServicioMuseFiltro _servicioFiltroMuse;
        private readonly IServicioAptitudes _servicioAptitudes;
        private readonly IServicioTalentos _servicioTalentos;
        private readonly IServicioVacantes _servicioVacantes;
        private readonly IServicioPerfiles _servicioPerfiles;

        public MuseFiltroController(IServicioMuseFiltro servicioFiltroMuse,
            IServicioAptitudes servicioAptitudes,
            IServicioVacantes servicioVacantes,
            IServicioTalentos servicioTalentos,
            IServicioPerfiles servicioPerfiles)
        {
            _servicioFiltroMuse = servicioFiltroMuse;
            _servicioAptitudes = servicioAptitudes;
            _servicioVacantes = servicioVacantes;
            _servicioTalentos = servicioTalentos;
            _servicioPerfiles = servicioPerfiles;
        }
        public ActionResult BuscadorMuse()
        {
            ViewBag.Aptitudes = ObtenerAptitudes();
            ViewBag.Talentos = ObtenerTalentos();
            ViewBag.Perfiles = ObtenerPerfiles();
            ViewBag.Vacantes = ObtenerVacantes();
            return View();
        }

        [HttpPost]
        public PartialViewResult BuscadorMuse(MuseFiltroInputModel entrada)
        {
            switch ((TipoFiltroMuse)entrada.Filtro)
            {
                case TipoFiltroMuse.Aptitudes:
                    var tpv = _servicioFiltroMuse.ObtenerUsandoAptitudes(entrada);
                    return PartialView("_partialAptitudesResultado", tpv);
                case TipoFiltroMuse.Talento:
                    var apv = _servicioFiltroMuse.ObtenerUsandoTalento(entrada);
                    return PartialView("_partialTalentoResultado", apv);
                case TipoFiltroMuse.Perfiles:
                    var tp = _servicioFiltroMuse.ObtenerUsandoPerfiles(entrada);
                    return PartialView("_partialPerfilesResultado", tp);
                case TipoFiltroMuse.Vacante:
                    var tv = _servicioFiltroMuse.ObtenerUsandoVacante(entrada);
                    return PartialView("_partialVacanteResultado", tv);

            }
            var resultado = _servicioFiltroMuse.ObtenerUsandoAptitudes(entrada);
            return PartialView("_partialPrueba");
        }

        #region CargadoresData
        public List<SelectListItem> ObtenerAptitudes()
        {
            var aptitudes = _servicioAptitudes.ObtenerAptitudes();
            return aptitudes.Select(a => new SelectListItem()
            {
                Text = a.Nombre,
                Value = a.AptitudID.ToString()
            }).ToList();
        }

        public List<SelectListItem> ObtenerTalentos()
        {
            var talentos = _servicioTalentos.ObtenerTalentos();
            return talentos.Select(t => new SelectListItem()
            {
                Text = t.NombreSimple,
                Value = t.TalentoID.ToString()
            }).ToList();
        }

        public List<SelectListItem> ObtenerPerfiles()
        {
            var perfiles = _servicioPerfiles.ObtenerPerfiles();
            return perfiles.Select(p => new SelectListItem()
            {
                Text = p.Nombre,
                Value = p.PerfilID.ToString()
            }).ToList();
        }

        public List<SelectListItem> ObtenerVacantes()
        {
            var vacantes = _servicioVacantes.ObtenerVacantes();
            return vacantes.Select(v => new SelectListItem()
            {
                Text = v.Nombre,
                Value = v.VacanteID.ToString()
            }).ToList();
        }
        #endregion
    }
}

TalentosApp/TalentosApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TalentosApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        var rootDir = document.location.href.substring(0, document.location.href.indexOf("/", 7) + 1);
    </script>


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TalentosApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Aptitudes", "ListadoAptitudesPaginado", "Aptitudes")</li>
                    <li>@Html.ActionLink("Perfiles", "ListadoPerfilesPaginado", "Perfiles")</li>
                    <li>@Html.ActionLink("Talentos", "ListadoTalentosPaginado", "Talentos")</li>
                    <li>@Html.ActionLink("Clientes", "ListadoClientesPaginado", "Clientes")</li>
                    <li>@Html.ActionLink("Vacantes", "ListadoVacantesPaginado", "Vacantes")</li>
                    <li>@Html.ActionLink("Muse","BuscadorMuse","MuseFiltro")</li>
                    <li>@Html.ActionLink("Nosotros", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TalentosApp</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>